### ISSUE TITLE
Great App!

### ISSUE THREAD

**Issue by FabianoLothor** [r3oath/burst-type.pro#106]
I'm learning Colemak and your app is f-amazing!

I just got a streak of 10, typing "information" beyond 100wpm, I can't believe, I had lost 7 times a streak of 9.

I started under 20wpm for this word and ended up with 10 streaks above 100wpm, that's so great!

tbh, I thought that I would never get there. hehe

I recorded everything: https://youtube.com/live/fn-e-wMs_Ec

**Comment by cgregurich** [comment]
Can you emulate layouts through this site?? You say you're learning colemak-- did you have to change that in your PC's settings or just in the website?

**Comment by r3oath** [comment]
Nice work! Glad you're enjoying the app :)
