### ISSUE TITLE
Non-stop getting "Recording" message

### ISSUE THREAD

**Issue by mbledkowski** [r3oath/burst-type.pro#21]
Hello,
I am non stop getting "Recording" message instead of my WPM, and I cannot continue. Tried on both Firefox and Brave (Chromium). I can give any debugging information that you may need, just tell me what should I copy.
![image](https://github.com/r3oath/burst-type.pro/assets/23295125/cabca7bd-60b6-47b3-94a9-03898dae9856)
![image](https://github.com/r3oath/burst-type.pro/assets/23295125/ad3f2cc0-95cf-4f90-af3b-7e00b4e09c76)

Best regards,
Maciej Błędkowski

**Comment by r3oath** [comment]
Hi Maciej, does it say you succeeded or failed once you've hit the spacebar? Or does it continue displaying "Recording" even when you've hit space?

**Comment by mbledkowski** [comment]
> Hi Maciej, does it say you succeeded or failed once you've hit the spacebar? Or does it continue displaying "Recording" even when you've hit space?

It says either "failed", or do not react at all. I do not remember whether "failed" message appears exactly after a spacebar press, I might check it later though.

**Comment by mbledkowski** [comment]
[Screencast from 2023-07-10 21-20-34.webm](https://github.com/r3oath/burst-type.pro/assets/23295125/83f7c21f-0eee-4e4f-be7d-2c3a0b141438)
Video showing that issue

**Comment by r3oath** [comment]
It looks like you're just hitting the wrong key sequence. Each word is considered complete when you type all its letters, followed by a space (standard burst training approach). So, for example, on the first word, "the", you'll need to type <T><H><E><SPACE>. You do not need to press the enter key (it does not do anything).

If you make any spelling mistakes or do not type the entire word + space in time, it will fail, and your streak will be reset.

**Comment by mbledkowski** [comment]
I tried out the website now, and it seems to work fine.
